source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AURUnlockSlider_Example', :exclusive => true do
  pod 'AURUnlockSlider', :path => '../'
end

target 'AURUnlockSlider_Tests', :exclusive => true do
  pod 'AURUnlockSlider', :path => '../'

  
end
